POST http://localhost:3000/blog-api/v1/admin/add-new
Content-Type: multipart/form-data

--boundary
Content-Disposition: form-data; name="text_field"

Text field value

--boundary
Content-Disposition: form-data; name="photo"; filename="photo.jpg"
Content-Type: image/jpeg

@/Users/oguzhan/Downloads/photo.jpg
--boundary--